// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hpivxliutwqdtdsytsvf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhwaXZ4bGl1dHdxZHRkc3l0c3ZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMDkzOTMsImV4cCI6MjA3MDU4NTM5M30.TbtARU2aVPMnx2-6qxmb-y_9EdeU-e-MDHbjLH4DMpc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});